# Generated by Django 2.1.3 on 2018-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('budget', models.IntegerField(max_length=100)),
                ('job_start_time', models.IntegerField(max_length=100)),
                ('pickup_available', models.BooleanField()),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
