# Generated by Django 2.1.3 on 2018-11-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_auto_20181119_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='job_start_time',
            field=models.IntegerField(default=100),
        ),
    ]
